
package com.tangfan.client.user;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "userService", targetNamespace = "http://www.tangfan.org/user")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param user
     * @throws UserException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.client.user.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.client.user.AddResponse")
    public void add(
        @WebParam(name = "user", targetNamespace = "")
        User user)
        throws UserException_Exception
    ;

    /**
     * 
     * @param username
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.client.user.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.client.user.DeleteResponse")
    public void delete(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @return
     *     returns java.util.List<com.tangfan.client.user.User>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.client.user.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.client.user.ListResponse")
    public List<User> list();

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns com.tangfan.client.user.User
     * @throws UserException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.client.user.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.client.user.LoginResponse")
    public User login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws UserException_Exception
    ;

    /**
     * 
     * @param file
     */
    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.client.user.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.client.user.UploadResponse")
    public void upload(
        @WebParam(name = "file", targetNamespace = "")
        byte[] file);

    /**
     * 
     * @param file
     */
    @WebMethod
    @RequestWrapper(localName = "binary", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.client.user.Binary")
    @ResponseWrapper(localName = "binaryResponse", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.client.user.BinaryResponse")
    public void binary(
        @WebParam(name = "file", targetNamespace = "http://www.tangfan.org/user")
        DataHandler file);

}
