
package com.tangfan.client.my;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyService", targetNamespace = "http://service.soap.tangfan.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyService {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.soap.tangfan.com/", className = "com.tangfan.client.my.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.soap.tangfan.com/", className = "com.tangfan.client.my.AddResponse")
    @Action(input = "http://service.soap.tangfan.com/MyService/addRequest", output = "http://service.soap.tangfan.com/MyService/addResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param authInfo
     * @param parameters
     * @return
     *     returns com.tangfan.client.my.ListResponse
     */
    @WebMethod
    @WebResult(name = "listResponse", targetNamespace = "http://service.soap.tangfan.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://service.soap.tangfan.com/MyService/listRequest", output = "http://service.soap.tangfan.com/MyService/listResponse")
    public ListResponse list(
        @WebParam(name = "list", targetNamespace = "http://service.soap.tangfan.com/", partName = "parameters")
        List parameters,
        @WebParam(name = "authInfo", targetNamespace = "http://service.soap.tangfan.com/", header = true, partName = "authInfo")
        String authInfo);

    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://service.soap.tangfan.com/", className = "com.tangfan.client.my.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://service.soap.tangfan.com/", className = "com.tangfan.client.my.AddUserResponse")
    @Action(input = "http://service.soap.tangfan.com/MyService/addUserRequest", output = "http://service.soap.tangfan.com/MyService/addUserResponse")
    public void addUser(
        @WebParam(name = "user", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<User> user);

    /**
     * 
     * @param userName
     * @param password
     * @return
     *     returns com.tangfan.client.my.User
     * @throws UserException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.soap.tangfan.com/", className = "com.tangfan.client.my.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.soap.tangfan.com/", className = "com.tangfan.client.my.LoginResponse")
    @Action(input = "http://service.soap.tangfan.com/MyService/loginRequest", output = "http://service.soap.tangfan.com/MyService/loginResponse", fault = {
        @FaultAction(className = UserException_Exception.class, value = "http://service.soap.tangfan.com/MyService/login/Fault/UserException")
    })
    public User login(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws UserException_Exception
    ;

}
