
package com.tangfan.soap.service;

import java.util.List;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlMimeType;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.tangfan.soap.exception.UserException;
import com.tangfan.soap.model.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "userService", targetNamespace = "http://www.tangfan.org/user")
public interface UserService {


    /**
     * 
     * @param user
     * @throws UserException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.soap.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.soap.service.AddResponse")
    public void add(
        @WebParam(name = "user", targetNamespace = "")
        User user)
        throws UserException
    ;

    /**
     * 
     * @param username
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.soap.service.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.soap.service.DeleteResponse")
    public void delete(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @return
     *     returns java.util.List<com.tangfan.soap.service.User>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.soap.service.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.soap.service.ListResponse")
    public List<User> list();

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns com.tangfan.soap.service.User
     * @throws UserException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.soap.service.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.soap.service.LoginResponse")
    public User login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws UserException
    ;

    /**
     * 
     * @param file
     */
    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.soap.service.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.soap.service.UploadResponse")
    public void upload(
        @WebParam(name = "file", targetNamespace = "http://www.tangfan.org/user")
        byte[] file);
    
    /**
     * 
     * @param file
     */
    @WebMethod
    @RequestWrapper(localName = "binary", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.soap.service.Binary")
    @ResponseWrapper(localName = "binaryResponse", targetNamespace = "http://www.tangfan.org/user", className = "com.tangfan.soap.service.BinaryResponse")
    public void binary(
        @WebParam(name = "file", targetNamespace = "http://www.tangfan.org/user")
        @XmlMimeType("application/octet-stream")DataHandler file);
    
}
