package com.tangfan.client.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2015-04-21T22:47:08.745+08:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
@WebServiceClient(name = "CxfServiceService", 
                  wsdlLocation = "http://localhost:8084/cxf?wsdl",
                  targetNamespace = "http://service.cxf.tangfan.com/") 
public class CxfServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.cxf.tangfan.com/", "CxfServiceService");
    public final static QName CxfServicePort = new QName("http://service.cxf.tangfan.com/", "CxfServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8084/cxf?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CxfServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8084/cxf?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CxfServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CxfServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxfServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CxfServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CxfServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CxfServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CxfService
     */
    @WebEndpoint(name = "CxfServicePort")
    public CxfService getCxfServicePort() {
        return super.getPort(CxfServicePort, CxfService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CxfService
     */
    @WebEndpoint(name = "CxfServicePort")
    public CxfService getCxfServicePort(WebServiceFeature... features) {
        return super.getPort(CxfServicePort, CxfService.class, features);
    }

}
