package com.tangfan.client.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2015-04-22T14:43:09.445+08:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
@WebService(targetNamespace = "http://service.cxf.tangfan.com/", name = "CxfService")
@XmlSeeAlso({ObjectFactory.class})
public interface CxfService {

    @WebResult(name = "hello", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.cxf.tangfan.com/", className = "com.tangfan.client.cxf.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.cxf.tangfan.com/", className = "com.tangfan.client.cxf.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
